"""Seed demo vitals + a primary condition for every patient that has none.

Idempotent: a patient that already has any VitalSign row is skipped, and
a patient that already has a Condition is left alone.

Usage:
    cd backend && source .venv/bin/activate && python -m scripts.seed_demo_vitals
"""
from __future__ import annotations

import asyncio
import random
from datetime import date, datetime, timedelta, timezone

from sqlalchemy import select

from app.db.session import AsyncSessionLocal
from app.models import Condition, Patient
from app.models.vital import VitalSign


# (metric, unit, latest_value, drift, count)
# Series is generated by jittering around `latest_value` going BACKWARDS in
# time, so the most recent reading is `latest_value` and older readings drift
# by ±`drift`.
VITAL_TEMPLATES: list[tuple[str, str, float, float, int]] = [
    ("blood_pressure_systolic",  "mmHg", 122,  6,   7),
    ("blood_pressure_diastolic", "mmHg",  78,  4,   7),
    ("heart_rate",               "bpm",   76,  5,   7),
    ("glucose",                  "mg/dL", 98,  10,  7),
    ("hemoglobin",               "g/dL",  13.8, 0.6, 7),
    ("weight",                   "kg",    62,  1.2, 7),
    ("height",                   "cm",   168,  0,   1),
    ("temperature",              "°C",   36.7, 0.2, 7),
    ("respiratory_rate",         "/min",  16,  2,   7),
]


def _series_for(latest: float, drift: float, count: int) -> list[float]:
    """Build a `count`-long list of readings, oldest first, ending at `latest`."""
    rng = random.Random(int(latest * 1000))
    out: list[float] = []
    cur = latest
    for _ in range(count):
        out.append(round(cur, 2))
        cur = cur + rng.uniform(-drift, drift)
    out.reverse()  # oldest → newest
    return out


async def seed() -> None:
    async with AsyncSessionLocal() as db:
        patients = (await db.execute(select(Patient))).scalars().all()
        if not patients:
            print("No patients found — run the main seed script first.")
            return

        now = datetime.now(timezone.utc)

        for p in patients:
            existing = (
                await db.execute(
                    select(VitalSign).where(VitalSign.patient_id == p.id).limit(1)
                )
            ).scalar_one_or_none()
            if existing:
                print(f"  skip {p.first_name} {p.last_name} — already has vitals")
                continue

            print(f"  seeding vitals for {p.first_name} {p.last_name}")
            for metric, unit, latest, drift, count in VITAL_TEMPLATES:
                series = _series_for(latest, drift, count)
                for idx, value in enumerate(series):
                    # idx 0 = oldest, idx count-1 = latest
                    age_days = (count - 1 - idx)
                    db.add(
                        VitalSign(
                            patient_id=p.id,
                            metric=metric,
                            value=value,
                            unit=unit,
                            recorded_at=now - timedelta(days=age_days),
                            source="seed",
                        )
                    )

            # Seed a primary condition only if the patient has none
            cond_exists = (
                await db.execute(
                    select(Condition).where(Condition.patient_id == p.id).limit(1)
                )
            ).scalar_one_or_none()
            if not cond_exists:
                db.add(
                    Condition(
                        patient_id=p.id,
                        name="Diabetes Mellitus",
                        icd10="E11.9",
                        onset_date=date.today() - timedelta(days=365 * 2),
                        status="active",
                    )
                )

        await db.commit()
        print("Done.")


if __name__ == "__main__":
    asyncio.run(seed())
