"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-26

The "initial" migration is intentionally written against Base.metadata
rather than autogenerated DDL. Reasons:

1. pgvector ships the extension binaries but doesn't auto-enable per
   database. We need `CREATE EXTENSION IF NOT EXISTS vector` BEFORE any
   table that uses VECTOR(n), and Alembic autogenerate doesn't emit it.

2. SQLAlchemy 2.0's typed models already produce the complete and
   canonical DDL via `Base.metadata.create_all`. Re-deriving every
   `op.create_table(...)` by hand for the ~14 tables (plus the pgvector
   column) is just a transcription opportunity for errors.

3. The downgrade is a clean `drop_all`. If a real downgrade matters for
   a future migration, that one can be hand-written normally.

Future migrations should be regular per-table `op.add_column` /
`op.alter_column` / etc. — autogenerate works correctly after this.
"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
from sqlalchemy import text

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector first — DocumentChunk.embedding is a VECTOR(1536) column.
    op.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))

    # Import models at function-time so the import side-effects don't run
    # at migration-load time (Alembic loads every revision file at startup).
    import app.models  # noqa: F401 — populates Base.metadata
    from app.db.base import Base

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    import app.models  # noqa: F401
    from app.db.base import Base

    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind, checkfirst=True)
    # Leave the pgvector extension alone — other databases may depend on it.
