from functools import lru_cache
from typing import Literal

from pydantic import Field, computed_field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",
    )

    PROJECT_NAME: str = "Padmavat"
    ENVIRONMENT: Literal["development", "staging", "production"] = "development"
    DEBUG: bool = True
    API_V1_PREFIX: str = "/api/v1"

    SECRET_KEY: str = Field(default="dev-secret-please-change-in-production-32chars")
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60
    REFRESH_TOKEN_EXPIRE_DAYS: int = 14

    POSTGRES_HOST: str = "localhost"
    POSTGRES_PORT: int = 5432
    POSTGRES_DB: str = "padmavat"
    POSTGRES_USER: str = "padmavat"
    POSTGRES_PASSWORD: str = "padmavat"

    # Async engine pool. Scale `DB_POOL_SIZE` with uvicorn worker
    # count; max_overflow gives burst capacity for spike traffic.
    DB_POOL_SIZE: int = 10
    DB_POOL_MAX_OVERFLOW: int = 20

    REDIS_URL: str = "redis://localhost:6379/0"
    CELERY_BROKER_URL: str = "redis://localhost:6379/1"
    CELERY_RESULT_BACKEND: str = "redis://localhost:6379/2"

    # LLM provider selection. One of: openai | groq | ollama | stub.
    # `stub` (or any unconfigured provider) returns deterministic
    # placeholder text so dev/CI keep working without a real key.
    LLM_PROVIDER: Literal["openai", "groq", "ollama", "stub", ""] = ""
    # Optional model overrides — leave blank to use the provider's default
    # (gpt-4o-mini / llama-3.3-70b-versatile / llama3.2:3b).
    LLM_MODEL_CHAT: str = ""
    LLM_MODEL_EMBED: str = ""

    # Provider credentials. Only the one matching LLM_PROVIDER is used at
    # runtime, but keeping all three lets us flip providers without
    # touching code.
    OPENAI_API_KEY: str = "sk-replace-me"
    GROQ_API_KEY: str = "gsk-replace-me"
    OLLAMA_BASE_URL: str = "http://localhost:11434/v1"

    # Legacy aliases — kept so existing code referencing
    # settings.OPENAI_MODEL_CHAT keeps working. New code should read
    # llm_client.chat_model instead.
    OPENAI_MODEL_CHAT: str = "gpt-4o-mini"
    OPENAI_MODEL_EMBED: str = "text-embedding-3-small"

    BACKEND_CORS_ORIGINS: str = "http://localhost:5173,http://localhost:3000"
    RATE_LIMIT_PER_MINUTE: int = 120

    # Base URL of the patient-portal Vite app — used in invite + reset
    # URLs generated by the patient auth service.
    PATIENT_PORTAL_URL: str = "http://localhost:5174"

    # Daily.co — telehealth + transcription. The HIPAA plan signs a
    # BAA that covers BOTH video and Deepgram-backed transcription.
    DAILY_API_KEY: str = ""
    DAILY_DOMAIN: str = ""  # e.g. "modern-ehr.daily.co"
    # Daily signs webhook payloads with this shared secret — keep blank
    # in dev to disable signature verification (logged warning).
    DAILY_WEBHOOK_SECRET: str = ""

    # Base URL of the provider portal — used in staff (user) invite +
    # password-reset URLs generated by the user-invite service.
    PROVIDER_PORTAL_URL: str = "http://localhost:5173"

    # ----- Email / SMTP ----------------------------------------------
    # When SMTP_HOST is unset, transactional emails are logged via
    # structlog instead of sent (so dev + CI work out of the box). In
    # production point at a HIPAA-compliant provider (AWS SES with
    # BAA, Postmark transactional, SendGrid Pro, Mailgun HIPAA).
    SMTP_HOST: str = ""
    SMTP_PORT: int = 587
    SMTP_USER: str = ""
    SMTP_PASSWORD: str = ""
    SMTP_USE_TLS: bool = True
    SMTP_FROM_EMAIL: str = "no-reply@modern-ehr.health"
    SMTP_FROM_NAME: str = "Modern EHR"

    @computed_field
    @property
    def DATABASE_URL(self) -> str:
        return (
            f"postgresql+asyncpg://{self.POSTGRES_USER}:{self.POSTGRES_PASSWORD}"
            f"@{self.POSTGRES_HOST}:{self.POSTGRES_PORT}/{self.POSTGRES_DB}"
        )

    @computed_field
    @property
    def SYNC_DATABASE_URL(self) -> str:
        return (
            f"postgresql+psycopg://{self.POSTGRES_USER}:{self.POSTGRES_PASSWORD}"
            f"@{self.POSTGRES_HOST}:{self.POSTGRES_PORT}/{self.POSTGRES_DB}"
        )

    @computed_field
    @property
    def cors_origins(self) -> list[str]:
        return [o.strip() for o in self.BACKEND_CORS_ORIGINS.split(",") if o.strip()]

    @model_validator(mode="after")
    def _enforce_prod_secrets(self) -> "Settings":
        # In production, refuse to boot with the dev-default secret key or a key
        # that's too short to be useful for HS256 (JWT spec recommends ≥ 32 bytes).
        if self.ENVIRONMENT == "production":
            if self.SECRET_KEY.startswith("dev-") or len(self.SECRET_KEY) < 32:
                raise ValueError(
                    "SECRET_KEY must be set to a strong production secret "
                    "(≥ 32 chars, not starting with 'dev-') when "
                    "ENVIRONMENT=production."
                )
            if self.POSTGRES_PASSWORD in {"padmavat", "symptra", "postgres", ""}:
                raise ValueError(
                    "POSTGRES_PASSWORD looks like a dev default; refusing to "
                    "boot with ENVIRONMENT=production."
                )
        return self


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
